### ISSUE TITLE
very first page of playground starts with error from missing `?`

### ISSUE THREAD

**Issue by extrajordanary** [MakeSchool-Tutorials/Intro-Functions-Swift#3]
<img width="717" alt="screen shot 2016-12-25 at 7 14 27 am" src="https://cloud.githubusercontent.com/assets/4017420/21468938/829ee1a0-ca72-11e6-8fd9-baae51c7e0ef.png">

**Comment by dionlarson** [comment]
Are you experiencing this issue in Xcode 8.2? I just tested it and cannot recreate with fresh playground. It's possible the issue was due to a syntax issue in the student code portion. Playgrounds occasionally highlight the wrong line/error.

**Comment by dionlarson** [comment]
Seems to be related to the new MBP with touchbar.

**Comment by extrajordanary** [comment]
> Seems to be related to the new MBP with touchbar

Actually, for a handful of  students, simply adding a `?` after `.liveView` did fix it and allow the playground to run. And not everyone got the issue (that I'm aware of, would need to confirm with Luke and Jason in case maybe it did affect everyone but we each helped diff folks and didn't notice). 

Wasn't until we started getting the folks for whom the `?` didn't solve the issue that we realized it might be a deeper bug.

Wasn't paying attention at the time, but now I'm guessing maybe it manifests itself a little differently based on touchbar vs non-touchbar-but-new mac vs older models (which perhaps had neither error).

**Comment by dionlarson** [comment]
Thanks for documenting more of this. Tested on late 14' MBP and mid 11' MBA in Capitan & Sierra running Xcode 8.2 & 8.2.1 with no issues.

Adding a `?` at the end of the LHS of an assignment _shouldn't_ be syntactically correct (or relevant) so not really sure where this might be coming from...

**Comment by extrajordanary** [comment]
> Adding a ? at the end of the LHS of an assignment shouldn't be syntactically correct

will try to see if I can remember/refind one of the students that this was a "fix" for and grab their laptop specs

**Comment by extrajordanary** [comment]
<img width="1402" alt="screen shot 2016-12-26 at 8 06 13 am" src="https://cloud.githubusercontent.com/assets/4017420/21473198/3cbc9daa-cb42-11e6-93cd-f377781dc081.png">

@dionlarson OSX version actually breaks on same issue, I see some Swizzle in action there
