### ISSUE TITLE
1. Introducing Functions

### ISSUE THREAD

**Issue by chgoodone** [MakeSchool-Tutorials/Intro-Functions-Swift#4]
The characters are too small to read, and it can not be zoomed up either.When I finish reading these contents my eyes feel very tired and uncomfortable.

**Comment by dionlarson** [comment]
Sorry!

Try going to `Xcode > Prefrences > Font and Color` to change the size.

**Comment by chgoodone** [comment]
Thank you so much,I have solved it.
