### ISSUE TITLE
1. Introducing Functions

### ISSUE THREAD

**Issue by GautamMandsorwale** [MakeSchool-Tutorials/Intro-Functions-Swift#5]
Hi Please find the screen shot attached for the error . 

I have just downloaded the zip file from this location - https://github.com/MakeSchool-Tutorials/Intro-Functions-Swift-Playground/archive/swift3.zip

And opened in Xcode. However not able to get pass it due to the error in attached screenshot.

I am new to swift/ios programming so can't resolve on my own.

Please guide. 
Thanks Again!
<img width="1276" alt="screen shot 2017-10-31 at 1 31 45 pm" src="https://user-images.githubusercontent.com/12850369/32213607-e7974d7c-be41-11e7-9e06-3fca707c1f7c.png">

**Comment by dionlarson** [comment]
Fixed in https://github.com/MakeSchool-Tutorials/Intro-Functions-Swift-Playground/commit/263ceb70129c0428ce3bf36639c4b096864b563d

You can download a fresh copy here:
https://github.com/MakeSchool-Tutorials/Intro-Functions-Swift-Playground/archive/swift4.zip
